name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # Upload workspace with 30-day retention
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .
          retention-days: 30

  Build:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Build
        run: npx nx build

  Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit

      # - name: E2E tests
      #   run: npm run test:e2e
