name: CI Workflow

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight UTC

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npx nx build

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            dist/
            node_modules/

      - name: Restore workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: reports/coverage/

      # - name: E2E tests
      #   run: npm run test:e2e
